import AVFoundation
import XCTest

@testable import Opus

final class OpusDecoderTests: XCTestCase {
	func testInit() throws {
		try AVAudioFormatTests.validFormats.forEach {
			_ = try Opus.Decoder(format: $0)
		}

		try AVAudioFormatTests.invalidFormats.forEach {
			XCTAssertThrowsError(try Opus.Decoder(format: $0)) { error in
				XCTAssertEqual(error as! Opus.Error, Opus.Error.badArgument)
			}
		}
	}

	func testCorruptedOpusDataThrowsInvalidPacketError() throws {
		guard let opusFormat = AVAudioFormat(opusPCMFormat: .int16, sampleRate: .opus16khz, channels: 1) else {
			XCTFail("Unable to generate desired opusFormat")
			return
		}

		let opusDecoder = try Opus.Decoder(format: opusFormat)
		// A corrupted, 40 bytes opus package, generated by a buggy Bluetooth piece of software. Other scenarios may also be the cause of a similar issue.
		let corruptedOpusData = Data([191, 232, 174, 215, 224, 130, 236, 126, 177, 204, 165, 85, 230, 201, 43, 16, 207, 120, 223, 247, 59, 117, 41, 235, 55, 96, 78, 68, 7, 207, 184, 255, 254, 0, 0, 0, 0, 0, 0, 0])

		XCTAssertThrowsError(try opusDecoder.decode(corruptedOpusData)) { error in
			guard let opusError = error as? Opus.Error else {
				XCTFail("Unable to cast error to Opus.Error")
				return
			}

			XCTAssertEqual(opusError, Opus.Error.invalidPacket)
		}
	}

	func testRejectsEmptyPacket() throws {
		let format = AVAudioFormat(opusPCMFormat: .float32, sampleRate: .opus48khz, channels: 2)!
		let decoder = try Opus.Decoder(format: format)

		XCTAssertThrowsError(try decoder.decode(Data())) { error in
			XCTAssertEqual(error as? Opus.Error, .badArgument)
		}
	}

	func testRejectsMismatchedOutputFormat() throws {
		let decoderFormat = AVAudioFormat(opusPCMFormat: .float32, sampleRate: .opus48khz, channels: 2)!
		let outputFormat = AVAudioFormat(opusPCMFormat: .float32, sampleRate: .opus48khz, channels: 1)!
		let output = AVAudioPCMBuffer(pcmFormat: outputFormat, frameCapacity: 960)!
		let decoder = try Opus.Decoder(format: decoderFormat)
		let packet: [UInt8] = [0]

		try packet.withUnsafeBufferPointer { packet in
			XCTAssertThrowsError(try decoder.decode(packet, to: output)) { error in
				XCTAssertEqual(error as? Opus.Error, .badArgument)
			}
		}
	}

	func testConcealsMissingPacket() throws {
		let format = AVAudioFormat(opusPCMFormat: .float32, sampleRate: .opus48khz, channels: 2)!
		let decoder = try Opus.Decoder(format: format)

		let output = try decoder.decodeMissingPacket(frameCapacity: 960)

		XCTAssertTrue(output.format.isEqual(format))
		XCTAssertEqual(output.frameLength, 960)
	}

	func testDecodesForwardErrorCorrectionPacket() throws {
		let format = AVAudioFormat(opusPCMFormat: .float32, sampleRate: .opus48khz, channels: 2)!
		let input = AVAudioPCMBuffer(pcmFormat: format, frameCapacity: 960)!
		input.frameLength = 960
		let encoder = try Opus.Encoder(format: format, application: .voip)
		try encoder.configure(.init(usesInbandFEC: true, expectedPacketLossPercentage: 20, signal: .voice))
		_ = try encoder.encode(input)
		let packet = try encoder.encode(input)

		let decoder = try Opus.Decoder(format: format)
		let output = try decoder.decode(packet, decodeFEC: true)
		XCTAssertEqual(output.frameLength, 960)
	}

	func testRejectsMalformedPacketCorpusWithoutCrashing() throws {
		let format = AVAudioFormat(opusPCMFormat: .float32, sampleRate: .opus48khz, channels: 2)!
		for length in 1...64 {
			let packet = Data((0..<length).map { UInt8(($0 * 37 + length * 17) & 0xff) })
			let decoder = try Opus.Decoder(format: format)
			_ = try? decoder.decode(packet)
		}
	}
}
