name: Swift

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/swift.yaml"
      - ".swift-format"
      - "Package.swift"
      - "Sources/**/*.swift"
      - "Tests/**/*.swift"
  pull_request:
    paths:
      - ".github/workflows/swift.yaml"
      - ".swift-format"
      - "Package.swift"
      - "Sources/**/*.swift"
      - "Tests/**/*.swift"

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install swift-format
        uses: Cyberbeni/install-swift-tool@v2
        with:
          url: https://github.com/apple/swift-format

      - name: Check Swift formatting
        run: swift-format lint -r Package.swift Sources Tests
